image: docker:dind

stages:
  - build

before_script:
  - env
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  tags:
    - beholder
  script:
    - ls /
    - pwd
    - docker build -f Dockerfile -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA:0:8} .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA:0:8}

